### ISSUE TITLE
Help wanted - Dynamic set field data

### ISSUE THREAD

**Issue by lgraji20** [venmo/business-rules-ui#2]
Am new to this site dont know where to post the help. could  you please help me how we can set a dynamic data in select option instead of static data like day of expiration and etc..

**Comment by gregeinfrank** [comment]
@lgraji20 This js library is meant to be used with our server-side python library https://github.com/venmo/business-rules. If you set up your server-side business rules and return back `export_rule_data` to this javascript front-end, you should be good to go.
